### ISSUE TITLE
Не запускается (крашится при запуске)

### ISSUE THREAD

**Issue by imnachar** [FlexxxerAlex/frametime-handler#1]
Win10 x64, последний билд. 
Скачал **0.1 Release**, запускаю FrameTimeHandler.exe — ничего не происходит.

Смотрю Event Viewer — там две ошибки:

1) Событие 1026, источник - .NET Runtime
Application: FrameTimeHandler.exe
CoreCLR Version: 4.700.20.26901
.NET Core Version: 3.1.6
Description: The process was terminated due to an unhandled exception.
Exception Info: System.InvalidOperationException: Sequence contains no matching element
   at System.Linq.ThrowHelper.ThrowNoMatchException()
   at System.Linq.Enumerable.First[TSource](IEnumerable`1 source, Func`2 predicate)
   at FrameTimeHandler.FTAnlzerInterop.FTAnlzer.<>c.<.cctor>b__9_0()
   at System.Lazy`1.ViaFactory(LazyThreadSafetyMode mode)
   at System.Lazy`1.ExecutionAndPublication(LazyHelper executionAndPublication, Boolean useDefaultConstructor)
   at System.Lazy`1.CreateValue()
   at System.Lazy`1.get_Value()
   at FrameTimeHandler.FTAnlzerInterop.FTAnlzer.get_SupportedPrograms()
   at FrameTimeHandler.ViewModels.MainWindowViewModel..ctor()
   at FrameTimeHandler.App.OnFrameworkInitializationCompleted()
   at Avalonia.Controls.AppBuilderBase`1.Setup()
   at Avalonia.Controls.AppBuilderBase`1.SetupWithLifetime(IApplicationLifetime lifetime)
   at Avalonia.ClassicDesktopStyleApplicationLifetimeExtensions.StartWithClassicDesktopLifetime[T](T builder, String[] args, ShutdownMode shutdownMode)
   at FrameTimeHandler.Program.Main(String[] args)

2) Событие 1000, источник — Application Error
Имя сбойного приложения: FrameTimeHandler.exe, версия: 0.1.0.0, метка времени: 0x5ee99cfc
Имя сбойного модуля: KERNELBASE.dll, версия: 10.0.19041.388, метка времени: 0x3cc24707
Код исключения: 0xe0434352
Смещение ошибки: 0x0000000000023e49
Идентификатор сбойного процесса: 0x2fac
Время запуска сбойного приложения: 0x01d6680f73ac04e1
Путь сбойного приложения: C:\FrameView\win-x64\FrameTimeHandler.exe
Путь сбойного модуля: C:\Windows\System32\KERNELBASE.dll
Идентификатор отчета: 98ce78ef-695d-447b-8f14-2247df9eb4e1
Полное имя сбойного пакета: 
Код приложения, связанного со сбойным пакетом:

**Comment by flexxxxer** [comment]
эта проблема связана с тем что в одной из используемых библиотек (PythonInterop) отсутствует ожидание окончания выполнения скрипта, из-за чего получение exit-code до окончания выполнения скрипта выкидывает исключение. данная ошибка в планах на скорейшее исправление, спасибо за ваше время и отчет

воспроизводиться ли на данный момент ошибка?

**Comment by flexxxxer** [comment]
только что проверил работоспособность подмуля [PythonInterop](https://github.com/FlexxxerAlex/PythonInterop), но он работает корректно. смею предположить, что на вашей системе не установлен интерпретатор языка Python. Проверяли ли вы его наличие?

**Comment by imnachar** [comment]
> смею предположить, что на вашей системе не установлен интерпретатор языка Python. Проверяли ли вы его наличие?

У меня была версия 3.7.4, установленная в комплекте вместе с каким-то софтом. Я удалил ее и установил вручную версию 3.8.5. Теперь ваша программа корректно работает. Спасибо!

**Comment by flexxxxer** [comment]
Сейчас проверил на версии 3.7.8, проблема не в версии языка Python. Данная проблема была вызвана некорректной установкой языка Python или вовсе его отсутствия в системе. Считаю, что проблема была решена
